#!/bin/bash

# Install mono
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
sudo apt-get update

sudo apt-get --assume-yes install mono-devel

# Install fsharp
sudo apt-get update
sudo apt-get --assume-yes install fsharp

# Get paket
wget -P .paket https://github.com/fsprojects/Paket/releases/download/5.113.0/paket.exe
mono .paket/paket.exe install

# Make scripts executable
chmod u+x build process stopall stopall-extreme master.py
